package com.example.flashmind.presentation.utils

// EDITAR LAS FLASHCARDS GENERADAS POR IA, BORRAR ALGUNA
// CRUD PARA CATEGORIAS
// CRUD PARA LECCIONES
//DISEÑO PARA LAS LECCIONES
//LOGIN CON FIREBASE GOOGLE
//TIMER AL FINAL DE LA LECCION
//MODO OSCURO
//) AIzaSyBtlIkRofL3TfCe5dJwso3t-ljoLHkQIqc